In [1]:
import torch

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
tensor_a

tensor([1, 2, 3, 4])

In [5]:
#Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [6]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [8]:
#Subtraction
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [9]:
#Multiplication
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [11]:
#Division
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [13]:
#Modulus
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [16]:
#Assignment _
tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])

In [17]:
tensor_a

tensor([11, 14, 17, 20])